# Generated by Django 5.2.5 on 2025-08-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(choices=[('Viga', 'Viga'), ('Pilar', 'Pilar'), ('Sapata', 'Sapata')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.TextField()),
                ('resultado_final', models.TextField()),
            ],
        ),
    ]
