# Generated by Django 5.2.5 on 2025-09-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo')),
            ],
            options={
                'verbose_name_plural': 'Configuração do Sistema',
            },
        ),
    ]
