# Generated by Django 5.2.5 on 2025-09-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0002_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7, verbose_name='Cor Principal'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema da Aplicação'),
        ),
    ]
