# Generated by Django 5.2.5 on 2025-10-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0003_systemconfiguration_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocalculo',
            name='input_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='historicocalculo',
            name='resultado_final',
            field=models.JSONField(),
        ),
    ]
